### ISSUE TITLE
"Modernize" quickstart

### ISSUE THREAD

**Issue by peter-madigan** [larpix/larpix-control#137]
We should update quickstart to use some of the common interface methods that we've adopted (e.g. load configurations from files vs. hard coded values, load controller configurations, auto-resolve daq server).

**Comment by samkohn** [comment]
Flagging that ``controller.chips`` is now unordered and so ``controller.chips.keys()`` will not necessarily be in the correct "daisy chain" order to ensure that all the ASICs are configured/disabled.
