### ISSUE TITLE
Plan for timestamp packets

### ISSUE THREAD

**Issue by samkohn** [larpix/larpix-control#151]
Timestamp packets should contain the number of clocks since the last reset/rollover, aka the "DAQ interval;" the approximate Unix timestamp to the nearest second, to check for obvious issues like a missing timestamp packet (would skip a reset or overflow); and the "chip key" corresponding to the DAQ board that produced the particular timestamp packet (that key would be of the form ``ID#-0-0``).

In terms of LArPix+HDF5 format, the ``timestamp`` field would hold the DAQ interval, the ``counter`` field would hold the Unix timestamp (4-byte timestamps work till year 2106), and the existing "chip key" fields would hold the DAQ board information.

**Comment by peter-madigan** [comment]
This issue has been addressed in PR #211

When interfacing with the PACMAN board, Timestamp packets are generated on each message corresponding to the UNIX timestamp contained in the message header. PACMAN heartbeat packets are contained within the new SyncPacket class, thus a message containing a heartbeat packet meets all of the criteria of this issue.
