### ISSUE TITLE
test_tutorial.py takes a long time on the second test

### ISSUE THREAD

**Issue by samkohn** [larpix/larpix-control#165]
Edit: second and third tests

**Comment by peter-madigan** [comment]
I think this might be because I am using a valid address for the ZMQ_IO class initialization - my guess is that there is some timeout period where it is trying to establish a connection. This fix is likely to use a designated "bad" address, e.g. 192.0.2.1 like what is used in the zmq_io tests.

**Comment by samkohn** [comment]
After much hunting, I have determined:

- The delay is only present when connecting to an address ending in ``.local``
- The delay is due to waiting for a background thread to finish executing. The thread starts during the ``socket.connect()`` call. I believe this is the bonjour / avahi networking driver timing out when it cannot find a connection.
- The delay stacks up if there are multiple sockets connecting.
- I believe the fact that the delay is not interrupted during ``socket.close`` or ``context.term`` is likely a bug. I'm not sure whether it's in pyzmq or libzmq.

The solution is to not use ``.local`` addresses during the tests
